unet:
  in_channels: 3
  out_channels: 3
  model_channels: 128
  channel_mult: [1, 2, 3, 4]
  res_blocks: 3
  attention_heads: 4
  attention_resolutions: [16, 8]
diffusion:
  schedule: cosine
  steps: 1000