target_time: 10hr
batch_rate: 2.00

warmup_batches: 500
# Turn down learning rate
# b/c I suspect it will increase convergence
# significantly
lr: 1.00*1e-4
cosine_factor: 1.2

batch_size: 140
micro_batches: 1
precision: amp

# For some reason, time is 21hrs
# instead of 10 although the math
# w/ the batch_rate checks out
checkpoints: 24
diffusion_logs: 200
evals: 120
